dist: trusty
sudo: false

language: node_js
node_js:
  - "16"

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test-headless
  - npm run build