dist: trusty
sudo: false

language: node_js
node_js:
  - "16"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run build
